# Generated by Django 5.1.2 on 2024-12-13 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_Colegio', '0004_alter_docente_asignaturas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='asignaturas',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='sistema_Colegio.docente'),
        ),
    ]
