# Generated by Django 5.1.2 on 2024-12-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_Colegio', '0005_remove_docente_asignaturas_asignatura_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='docentes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='estudiantes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nodocentes',
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
