# Generated by Django 5.1.2 on 2024-12-14 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_Colegio', '0008_asistencia_asignatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotacion',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='anotacion',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]