# Generated by Django 5.1.2 on 2024-12-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_Colegio', '0009_rename_texto_anotacion_descripcion_anotacion_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
