# Generated by Django 5.1.2 on 2024-12-14 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_Colegio', '0010_alter_anotacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
